import type {
  AccessType,
  ArtworkStatus,
  Category,
  Difficulty,
  Tutorial,
  TutorialLevel,
} from "@/types/tutorial";

import { DIFFICULTIES } from "./levels";

/**
 * Phase 1 mock content. Replaced by Supabase in Phase 2.
 *
 * Image keys follow the R2 layout from PROJECT_PLAN.md §20 and resolve to files
 * under /public/mock-assets. Real worksheets are named `<slug>-<difficulty>.png`
 * inside `tutorials/<slug>/<difficulty>/`; dog breeds keep all of their sheets
 * together in `tutorials/dog/<breed>/` instead (see `dogBreed`). Levels without
 * artwork yet use labelled placeholder frames generated by
 * scripts/make-placeholders.mjs.
 */

export const mockCategories: Category[] = [
  {
    id: "cat_beach-ocean",
    name: "Beach & Ocean",
    slug: "beach-ocean",
    description:
      "Coconut trees, boats, lighthouses and everything else you find by the sea.",
    imageKey: null,
    sortOrder: 1,
  },
  {
    id: "cat_animals",
    name: "Animals",
    slug: "animals",
    description:
      "Pets, wildlife, birds and insects, from simple shapes to fur and feathers.",
    imageKey: null,
    sortOrder: 2,
  },
  {
    id: "cat_nature",
    name: "Nature",
    slug: "nature",
    description: "Trees, leaves, mountains and skies.",
    imageKey: null,
    sortOrder: 3,
  },
  {
    id: "cat_flowers",
    name: "Flowers",
    slug: "flowers",
    description: "Single blooms and full bouquets, petal by petal.",
    imageKey: null,
    sortOrder: 4,
  },
  {
    id: "cat_landscapes",
    name: "Landscapes",
    slug: "landscapes",
    description: "Horizons, hills, sunsets and open skies.",
    imageKey: null,
    sortOrder: 5,
  },
  {
    id: "cat_buildings",
    name: "Buildings",
    slug: "buildings",
    description: "Houses, towers and lighthouses, with simple perspective.",
    imageKey: null,
    sortOrder: 6,
  },
  {
    id: "cat_objects",
    name: "Objects",
    slug: "objects",
    description: "Everyday things that make great practice subjects.",
    imageKey: null,
    sortOrder: 7,
  },
];

const PLACEHOLDER_WORKSHEET = "tutorial-mock.svg";
const PLACEHOLDER_PREVIEW = "preview-mock.svg";
const PLACEHOLDER_THUMBNAIL = "thumbnail/thumbnail.svg";

interface LevelInput {
  access: AccessType;
  steps?: number;
  intro?: string;
  /** "missing" means the level row exists but no artwork has been uploaded yet. */
  artwork?: ArtworkStatus | "missing";
  /** Worksheet file name inside the level's asset folder. Defaults to the placeholder. */
  file?: string;
  /** Public preview for premium levels: `true` for the placeholder, or a file name in the level folder. */
  preview?: boolean | string;
}

function level(
  slug: string,
  difficulty: Difficulty,
  /** Folder under tutorials/ that holds this level's files. */
  folder: string,
  input: LevelInput,
): TutorialLevel {
  const artwork = input.artwork ?? "published";
  const hasImage = artwork !== "missing";
  const file = input.file ?? PLACEHOLDER_WORKSHEET;
  const previewFile =
    input.preview === true
      ? PLACEHOLDER_PREVIEW
      : input.preview
        ? input.preview
        : null;
  return {
    id: `lvl_${slug}_${difficulty}`,
    tutorialId: `tut_${slug}`,
    difficulty,
    accessType: input.access,
    tutorialImageKey: hasImage ? `tutorials/${folder}/${file}` : null,
    previewImageKey: previewFile ? `tutorials/${folder}/${previewFile}` : null,
    printableFileKey: null,
    introduction: input.intro ?? null,
    stepCount: input.steps ?? null,
    artworkStatus: artwork === "missing" ? "draft" : artwork,
  };
}

interface TutorialInput {
  slug: string;
  title: string;
  categoryId: string;
  description: string;
  status?: Tutorial["status"];
  featured?: boolean;
  publishedAt?: string;
  /**
   * One folder under tutorials/ that holds every level's files side by side.
   * By default each level has its own folder, `<slug>/<difficulty>/`.
   */
  assetFolder?: string;
  /** Thumbnail path relative to the subject's folder under tutorials/. Defaults to the placeholder. */
  thumbnail?: string;
  levels: Partial<Record<Difficulty, LevelInput>>;
}

function tutorial(input: TutorialInput): Tutorial {
  const subjectFolder = input.assetFolder ?? input.slug;
  return {
    id: `tut_${input.slug}`,
    title: input.title,
    slug: input.slug,
    description: input.description,
    categoryId: input.categoryId,
    featuredImageKey: `tutorials/${subjectFolder}/${input.thumbnail ?? PLACEHOLDER_THUMBNAIL}`,
    seoTitle: null,
    seoDescription: null,
    status: input.status ?? "published",
    featured: input.featured ?? false,
    publishedAt: input.publishedAt ?? null,
    levels: (Object.entries(input.levels) as [Difficulty, LevelInput][]).map(
      ([difficulty, levelInput]) =>
        level(
          input.slug,
          difficulty,
          input.assetFolder ?? `${input.slug}/${difficulty}`,
          levelInput,
        ),
    ),
  };
}

// TODO(content): the levels marked "free for now" are meant to be premium. Switch
// them back to "premium" and add `preview: "<file>"` once a public preview sheet
// (for example the first row of steps) has been exported for each of them.

type DogLevelInput = Omit<LevelInput, "access" | "artwork" | "file"> & {
  access?: AccessType;
};

interface DogBreedInput {
  /** Breed slug, e.g. "golden-retriever". Doubles as the tutorial slug and the asset folder name. */
  breed: string;
  title: string;
  description: string;
  featured?: boolean;
  publishedAt: string;
  levels: Partial<Record<Difficulty, DogLevelInput>>;
}

/**
 * Each dog breed is its own subject in the Animals category. Its worksheets are
 * organised by breed rather than by difficulty,
 * `tutorials/dog/<breed>/dog-<breed>-<difficulty>.png`, and the easiest sheet
 * doubles as the thumbnail. Every level is free for now: the advanced sheets
 * are meant to be premium once they have a public preview (see the TODO above).
 */
function dogBreed(input: DogBreedInput): Tutorial {
  const file = (difficulty: Difficulty) =>
    `dog-${input.breed}-${difficulty}.png`;
  const levels: Partial<Record<Difficulty, LevelInput>> = {};
  for (const difficulty of DIFFICULTIES) {
    const levelInput = input.levels[difficulty];
    if (levelInput) {
      levels[difficulty] = {
        ...levelInput,
        access: levelInput.access ?? "free",
        file: file(difficulty),
      };
    }
  }
  const easiest = DIFFICULTIES.find((difficulty) => input.levels[difficulty]);
  if (!easiest) {
    throw new Error(`Dog breed "${input.breed}" has no levels`);
  }
  return tutorial({
    slug: input.breed,
    title: input.title,
    categoryId: "cat_animals",
    description: input.description,
    featured: input.featured,
    publishedAt: input.publishedAt,
    assetFolder: `dog/${input.breed}`,
    thumbnail: file(easiest),
    levels,
  });
}

export const mockTutorials: Tutorial[] = [
  tutorial({
    slug: "coconut-tree",
    title: "Coconut Tree",
    categoryId: "cat_beach-ocean",
    description:
      "A leaning trunk, a crown of fronds and a few coconuts. The classic tropical tree at three levels of detail.",
    featured: true,
    publishedAt: "2026-08-10T09:00:00.000Z",
    thumbnail: "beginner/coconut-tree-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "coconut-tree-beginner.png",
        intro:
          "One curved line for the trunk, a small crown, then the fronds one set at a time. Six steps that end with trunk texture and a simple shoreline.",
      },
      intermediate: {
        access: "free",
        steps: 6,
        file: "coconut-tree-intermediate.png",
        intro:
          "The same tree with a thicker, tapered trunk, overlapping fronds, leaf strands and a cluster of coconuts. Six steps, finishing with sand, sea and a distant island.",
      },
      advanced: {
        access: "free", // free for now, see TODO above
        steps: 12,
        file: "coconut-tree-advanced.png",
        intro:
          "Guide lines, a textured trunk and a full crown built frond by frond, then shading, ground details and a beach background. Twelve steps, drawn lightly at first.",
      },
    },
  }),
  tutorial({
    slug: "sunset",
    title: "Sunset",
    categoryId: "cat_landscapes",
    description:
      "Sky bands, a low sun and a calm sea. A relaxing subject that teaches simple shading.",
    featured: true,
    publishedAt: "2026-08-14T09:00:00.000Z",
    thumbnail: "beginner/sunset-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "sunset-beginner.png",
        intro:
          "A horizon line, a half-circle sun and its reflection, a few waves, a curved beach and some final details. Six steps.",
      },
      intermediate: { access: "premium", artwork: "missing" },
      advanced: {
        access: "free", // free for now, see TODO above
        steps: 12,
        file: "sunset-advanced.png",
        intro:
          "Horizon, sun and reflection first, then clouds, distant land, palm leaves in the foreground, shading and highlights. Twelve steps.",
      },
    },
  }),
  tutorial({
    slug: "boat-on-shore",
    title: "Boat on a Shore",
    categoryId: "cat_beach-ocean",
    description:
      "A small boat pulled up on the sand, from a simple outline to weathered planks.",
    publishedAt: "2026-08-18T09:00:00.000Z",
    thumbnail: "beginner/boat-on-shore-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "boat-on-shore-beginner.png",
        intro:
          "A curved horizon, a wavy shoreline and a simple bowl-shaped hull, then the rim, a post with a rope and sand details. Six steps.",
      },
      intermediate: {
        access: "free", // free for now, see TODO above
        steps: 6,
        file: "boat-on-shore-intermediate.png",
        intro:
          "A curving shoreline, a hull with planks and seats, a rope on the front post, then waves, sand texture, clouds and a distant island. Six steps.",
      },
    },
  }),
  tutorial({
    slug: "butterfly",
    title: "Butterfly",
    categoryId: "cat_animals",
    description:
      "Symmetry practice with an easy wing shape and a pattern you can make your own.",
    publishedAt: "2026-08-22T09:00:00.000Z",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        intro:
          "Symmetrical wings from two ovals and a body. Six steps, with a simple pattern to finish.",
      },
    },
  }),
  tutorial({
    slug: "lighthouse",
    title: "Lighthouse",
    categoryId: "cat_buildings",
    description:
      "A tall tower on the rocks, from simple stripes and waves to stone texture, a keeper's house and a full seascape.",
    featured: true,
    publishedAt: "2026-08-30T09:00:00.000Z",
    // Only three sheets, so they sit flat in tutorials/lighthouse/ instead of per-level folders.
    assetFolder: "lighthouse",
    thumbnail: "lighthouse-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "lighthouse-beginner.png",
        intro:
          "A tall trapezoid, a small roof and platform on top, then windows, horizontal stripes, rocks at the base and a few wavy water lines. Six steps.",
      },
      intermediate: {
        access: "free", // free for now, see TODO above
        steps: 6,
        file: "lighthouse-intermediate.png",
        intro:
          "Block in the composition with a horizon line, then the tower with its platform and lantern room, windows, railing and door, a rocky foreground with a path and fence posts, stone texture and shading, and finally waves, distant land, clouds and birds. Six steps.",
      },
      advanced: {
        access: "free", // free for now, see TODO above
        steps: 12,
        file: "lighthouse-advanced.png",
        intro:
          "Guide lines and basic shapes, a refined structure with railing, windows and door, then the rocky base and a small keeper's house, stone texture, contours, shading, the sea, clouds, coastline and birds, and final touches. Twelve steps, drawn lightly at first.",
      },
    },
  }),

  // Dog breeds, in the order their sheets were drawn.
  dogBreed({
    breed: "pug",
    title: "Pug",
    description:
      "A stocky little dog with a wrinkled face, folded ears and a curled tail, from six simple shapes to a fully shaded portrait.",
    publishedAt: "2026-09-05T19:18:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle for the head and an oval for the body, simple legs, then the folded ears and curled tail, the face and a few wrinkle lines. Six steps.",
      },
      intermediate: {
        steps: 10,
        intro:
          "Pose and guides, a refined body, the head and its wrinkled face, then legs and paws, skin folds, short fur, shading and a patch of grass. Ten steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, a boxy head construction, then the wrinkled face, body structure, fur outlines, texture, shading, a ground shadow and final details. Twelve steps, drawn lightly at first.",
      },
    },
  }),
  dogBreed({
    breed: "labrador-retriever",
    title: "Labrador Retriever",
    description:
      "A sturdy, friendly labrador standing side-on. Simple shapes first, then muscle, short fur and shading.",
    publishedAt: "2026-09-05T19:24:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle and an oval, four simple legs, floppy ears and a tail, then the face and a few detail lines. Six steps.",
      },
      intermediate: {
        steps: 10,
        intro:
          "Pose and guides, refined contours, the head and face in detail, legs and paws, muscle definition, short fur, shading and a simple background. Ten steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, head construction and details, then body structure, a refined form, the short dense coat, shading, a ground shadow and a simple background. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "golden-retriever",
    title: "Golden Retriever",
    description:
      "A golden retriever with feathered fur and a happy face. Start with circles, then build up the long coat and shading.",
    featured: true,
    publishedAt: "2026-09-05T19:25:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "Head and body from a circle and an oval, then legs, floppy ears and a feathered tail, the face and some fur details. Six steps.",
      },
      intermediate: {
        steps: 10,
        intro:
          "Pose and guides, refined contours, the head and face, legs and paws, then the long wavy coat in two passes, shading and a grassy scene with hills. Ten steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines, proportions and head construction, then body structure, fur outlines, the feathered coat, facial details, shading, a ground shadow and a background. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "border-collie",
    title: "Border Collie",
    description:
      "A border collie mid-stride, with its white blaze and thick coat. Six easy steps, or a full realistic drawing at advanced.",
    publishedAt: "2026-09-05T19:26:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle, an oval and simple legs, then the ears and bushy tail, the face and the collie's fur markings. Six steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, a boxy head, then body structure, fur outlines, the black and white coat with its long fur texture, shading, a ground shadow and final details. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "german-shepherd",
    title: "German Shepherd",
    description:
      "A german shepherd with upright ears and a sloping back. Cartoon-simple at beginner, fully rendered at advanced.",
    publishedAt: "2026-09-05T19:27:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle and an oval, simple legs, upright ears and a low tail, then the face and the fur markings. Six steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, the long muzzle and upright ears, then body structure, fur outlines, the saddle markings, shading, a ground shadow and a background. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "poodle",
    title: "Poodle",
    description:
      "A poodle with its classic clipped coat: topknot, fluffy ears and pom-pom legs, drawn with simple curls first and detailed texture later.",
    publishedAt: "2026-09-05T19:29:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle, an oval and simple legs, then the fluffy ears, topknot and tail, the face and the pom-pom fur on the legs. Six steps.",
      },
      intermediate: {
        steps: 10,
        intro:
          "Pose and guides, a refined body, the head with its long ears, the face, legs and paws, then the curly coat and clipped trim, shading and a garden background. Ten steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, head construction with the topknot, then body structure, the clipped coat outlined and textured curl by curl, shading, a ground shadow and final details. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "husky",
    title: "Husky",
    description:
      "A husky with pointed ears, a bushy curled tail and the classic mask markings. Six simple steps.",
    publishedAt: "2026-09-05T19:31:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle and an oval, simple legs, pointed ears and a curled bushy tail, then the face and the husky's mask markings. Six steps.",
      },
    },
  }),
  dogBreed({
    breed: "pitbull",
    title: "Pitbull",
    description:
      "A muscular pitbull with a broad head and folded ears. Simple shapes, then muscle lines, short fur and shading.",
    publishedAt: "2026-09-05T19:42:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle and an oval, sturdy legs, small folded ears and a tail, then the face and a few muscle lines. Six steps.",
      },
      intermediate: {
        steps: 10,
        intro:
          "Pose and guides, refined contours, the head with folded ears, the face, legs and paws, muscle definition, short fur, shading and a simple scene. Ten steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, a broad head, then the muscular body structure, a refined form, short fur, facial details, shading, a ground shadow and a background. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "malinois",
    title: "Malinois",
    description:
      "A Belgian malinois with tall pointed ears and a dark muzzle, drawn from a few simple shapes in six steps.",
    publishedAt: "2026-09-05T19:46:00.000Z",
    levels: {
      beginner: {
        steps: 6,
        intro:
          "A circle and an oval, simple legs, tall pointed ears and a tail, then the face and the dark muzzle markings. Six steps.",
      },
    },
  }),
  dogBreed({
    breed: "dachshund",
    title: "Dachshund",
    description:
      "A long-bodied dachshund with floppy ears and short legs, from a clean outline to short fur, shading and a garden fence.",
    publishedAt: "2026-09-05T20:25:00.000Z",
    levels: {
      intermediate: {
        steps: 10,
        intro:
          "Pose and guides, the long low body, the head with floppy ears, the face, legs and paws, muscle definition, short smooth fur, shading and a fence in the background. Ten steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, the long body and box-shaped muzzle, then body structure, fur outlines, facial details, short fur texture, shading, a ground shadow and final details. Twelve steps.",
      },
    },
  }),
  dogBreed({
    breed: "spitz",
    title: "Spitz",
    description:
      "A fluffy white spitz with a curled tail, a fox-like face and a thick double coat. Fur texture is the whole lesson here.",
    publishedAt: "2026-09-05T20:39:00.000Z",
    levels: {
      intermediate: {
        steps: 6,
        intro:
          "Pose and guides, a refined body with pointed ears, the face, then the thick fluffy fur in two passes and a simple background. Six steps.",
      },
      advanced: {
        steps: 12,
        intro:
          "Guide lines and proportions, the wedge-shaped head, then body structure, fur outlines, the thick double coat, facial details, shading, a ground shadow and final details. Twelve steps.",
      },
    },
  }),

  // Draft subject: must never appear on public pages.
  tutorial({
    slug: "palm-tree",
    title: "Palm Tree",
    categoryId: "cat_beach-ocean",
    description: "A tall, slender palm with a small crown. Not published yet.",
    status: "draft",
    levels: {
      beginner: { access: "free", steps: 6 },
    },
  }),
];
