import type {
  AccessType,
  ArtworkStatus,
  Category,
  Difficulty,
  Tutorial,
  TutorialLevel,
} from "@/types/tutorial";

/**
 * Phase 1 mock content. Replaced by Supabase in Phase 2.
 *
 * Image keys follow the R2 layout from PROJECT_PLAN.md §20 and resolve to files
 * under /public/mock-assets. Real worksheets are named `<slug>-<difficulty>.png`
 * inside `tutorials/<slug>/<difficulty>/`; levels without artwork yet use
 * labelled placeholder frames generated by scripts/make-placeholders.mjs.
 */

export const mockCategories: Category[] = [
  {
    id: "cat_beach-ocean",
    name: "Beach & Ocean",
    slug: "beach-ocean",
    description:
      "Coconut trees, boats, lighthouses and everything else you find by the sea.",
    imageKey: null,
    sortOrder: 1,
  },
  {
    id: "cat_animals",
    name: "Animals",
    slug: "animals",
    description:
      "Pets, wildlife, birds and insects, from simple shapes to fur and feathers.",
    imageKey: null,
    sortOrder: 2,
  },
  {
    id: "cat_nature",
    name: "Nature",
    slug: "nature",
    description: "Trees, leaves, mountains and skies.",
    imageKey: null,
    sortOrder: 3,
  },
  {
    id: "cat_flowers",
    name: "Flowers",
    slug: "flowers",
    description: "Single blooms and full bouquets, petal by petal.",
    imageKey: null,
    sortOrder: 4,
  },
  {
    id: "cat_landscapes",
    name: "Landscapes",
    slug: "landscapes",
    description: "Horizons, hills, sunsets and open skies.",
    imageKey: null,
    sortOrder: 5,
  },
  {
    id: "cat_buildings",
    name: "Buildings",
    slug: "buildings",
    description: "Houses, towers and lighthouses, with simple perspective.",
    imageKey: null,
    sortOrder: 6,
  },
  {
    id: "cat_objects",
    name: "Objects",
    slug: "objects",
    description: "Everyday things that make great practice subjects.",
    imageKey: null,
    sortOrder: 7,
  },
];

const PLACEHOLDER_WORKSHEET = "tutorial-mock.svg";
const PLACEHOLDER_PREVIEW = "preview-mock.svg";
const PLACEHOLDER_THUMBNAIL = "thumbnail/thumbnail.svg";

interface LevelInput {
  access: AccessType;
  steps?: number;
  intro?: string;
  /** "missing" means the level row exists but no artwork has been uploaded yet. */
  artwork?: ArtworkStatus | "missing";
  /** Worksheet file name inside tutorials/<slug>/<difficulty>/. Defaults to the placeholder. */
  file?: string;
  /** Public preview for premium levels: `true` for the placeholder, or a file name in the level folder. */
  preview?: boolean | string;
}

function level(
  slug: string,
  difficulty: Difficulty,
  input: LevelInput,
): TutorialLevel {
  const artwork = input.artwork ?? "published";
  const hasImage = artwork !== "missing";
  const file = input.file ?? PLACEHOLDER_WORKSHEET;
  const previewFile =
    input.preview === true
      ? PLACEHOLDER_PREVIEW
      : input.preview
        ? input.preview
        : null;
  return {
    id: `lvl_${slug}_${difficulty}`,
    tutorialId: `tut_${slug}`,
    difficulty,
    accessType: input.access,
    tutorialImageKey: hasImage
      ? `tutorials/${slug}/${difficulty}/${file}`
      : null,
    previewImageKey: previewFile
      ? `tutorials/${slug}/${difficulty}/${previewFile}`
      : null,
    printableFileKey: null,
    introduction: input.intro ?? null,
    stepCount: input.steps ?? null,
    artworkStatus: artwork === "missing" ? "draft" : artwork,
  };
}

interface TutorialInput {
  slug: string;
  title: string;
  categoryId: string;
  description: string;
  status?: Tutorial["status"];
  featured?: boolean;
  publishedAt?: string;
  /** Thumbnail path relative to tutorials/<slug>/. Defaults to the placeholder. */
  thumbnail?: string;
  levels: Partial<Record<Difficulty, LevelInput>>;
}

function tutorial(input: TutorialInput): Tutorial {
  return {
    id: `tut_${input.slug}`,
    title: input.title,
    slug: input.slug,
    description: input.description,
    categoryId: input.categoryId,
    featuredImageKey: `tutorials/${input.slug}/${input.thumbnail ?? PLACEHOLDER_THUMBNAIL}`,
    seoTitle: null,
    seoDescription: null,
    status: input.status ?? "published",
    featured: input.featured ?? false,
    publishedAt: input.publishedAt ?? null,
    levels: (Object.entries(input.levels) as [Difficulty, LevelInput][]).map(
      ([difficulty, levelInput]) => level(input.slug, difficulty, levelInput),
    ),
  };
}

// TODO(content): the levels marked "free for now" are meant to be premium. Switch
// them back to "premium" and add `preview: "<file>"` once a public preview sheet
// (for example the first row of steps) has been exported for each of them.

export const mockTutorials: Tutorial[] = [
  tutorial({
    slug: "coconut-tree",
    title: "Coconut Tree",
    categoryId: "cat_beach-ocean",
    description:
      "A leaning trunk, a crown of fronds and a few coconuts. The classic tropical tree at three levels of detail.",
    featured: true,
    publishedAt: "2026-08-10T09:00:00.000Z",
    thumbnail: "beginner/coconut-tree-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "coconut-tree-beginner.png",
        intro:
          "One curved line for the trunk, a small crown, then the fronds one set at a time. Six steps that end with trunk texture and a simple shoreline.",
      },
      intermediate: {
        access: "free",
        steps: 6,
        file: "coconut-tree-intermediate.png",
        intro:
          "The same tree with a thicker, tapered trunk, overlapping fronds, leaf strands and a cluster of coconuts. Six steps, finishing with sand, sea and a distant island.",
      },
      advanced: {
        access: "free", // free for now, see TODO above
        steps: 12,
        file: "coconut-tree-advanced.png",
        intro:
          "Guide lines, a textured trunk and a full crown built frond by frond, then shading, ground details and a beach background. Twelve steps, drawn lightly at first.",
      },
    },
  }),
  tutorial({
    slug: "sunset",
    title: "Sunset",
    categoryId: "cat_landscapes",
    description:
      "Sky bands, a low sun and a calm sea. A relaxing subject that teaches simple shading.",
    featured: true,
    publishedAt: "2026-08-14T09:00:00.000Z",
    thumbnail: "beginner/sunset-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "sunset-beginner.png",
        intro:
          "A horizon line, a half-circle sun and its reflection, a few waves, a curved beach and some final details. Six steps.",
      },
      intermediate: { access: "premium", artwork: "missing" },
      advanced: {
        access: "free", // free for now, see TODO above
        steps: 12,
        file: "sunset-advanced.png",
        intro:
          "Horizon, sun and reflection first, then clouds, distant land, palm leaves in the foreground, shading and highlights. Twelve steps.",
      },
    },
  }),
  tutorial({
    slug: "boat-on-shore",
    title: "Boat on a Shore",
    categoryId: "cat_beach-ocean",
    description:
      "A small boat pulled up on the sand, from a simple outline to weathered planks.",
    publishedAt: "2026-08-18T09:00:00.000Z",
    thumbnail: "beginner/boat-on-shore-beginner.png",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        file: "boat-on-shore-beginner.png",
        intro:
          "A curved horizon, a wavy shoreline and a simple bowl-shaped hull, then the rim, a post with a rope and sand details. Six steps.",
      },
      intermediate: {
        access: "free", // free for now, see TODO above
        steps: 6,
        file: "boat-on-shore-intermediate.png",
        intro:
          "A curving shoreline, a hull with planks and seats, a rope on the front post, then waves, sand texture, clouds and a distant island. Six steps.",
      },
    },
  }),
  tutorial({
    slug: "butterfly",
    title: "Butterfly",
    categoryId: "cat_animals",
    description:
      "Symmetry practice with an easy wing shape and a pattern you can make your own.",
    publishedAt: "2026-08-22T09:00:00.000Z",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        intro:
          "Symmetrical wings from two ovals and a body. Six steps, with a simple pattern to finish.",
      },
    },
  }),
  tutorial({
    slug: "dog",
    title: "Dog",
    categoryId: "cat_animals",
    description:
      "A friendly sitting dog. Start with simple shapes, then work up to fur and expression.",
    featured: true,
    publishedAt: "2026-08-26T09:00:00.000Z",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        intro:
          "A sitting dog built from circles and a rounded muzzle. Six friendly steps.",
      },
      intermediate: {
        access: "premium",
        steps: 6,
        preview: true,
        intro:
          "Add floppy ears, a collar and the first fur texture. Six steps.",
      },
      advanced: {
        access: "free",
        steps: 12,
        intro:
          "A full portrait with layered fur, a wet nose and expressive eyes. Twelve steps, free as a sample of our advanced tutorials.",
      },
    },
  }),
  tutorial({
    slug: "lighthouse",
    title: "Lighthouse",
    categoryId: "cat_buildings",
    description:
      "A tall striped tower on the rocks, with railings, windows and waves.",
    featured: true,
    publishedAt: "2026-08-30T09:00:00.000Z",
    levels: {
      beginner: {
        access: "free",
        steps: 6,
        intro: "A tapered tower, a lantern room and a rocky base. Six steps.",
      },
      intermediate: {
        access: "premium",
        steps: 6,
        preview: true,
        intro:
          "Stripes, railings, windows and a rocky shoreline with spray. Six steps.",
      },
      advanced: { access: "premium", artwork: "missing" },
    },
  }),
  // Draft subject: must never appear on public pages.
  tutorial({
    slug: "palm-tree",
    title: "Palm Tree",
    categoryId: "cat_beach-ocean",
    description: "A tall, slender palm with a small crown. Not published yet.",
    status: "draft",
    levels: {
      beginner: { access: "free", steps: 6 },
    },
  }),
];
